-- Illuminate QR Ticket & Pass Validation System Schema
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_ADMIN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ticket_id VARCHAR(100) NOT NULL UNIQUE,
    participant_name VARCHAR(150) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(50),
    qr_token VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    checked_in BOOLEAN NOT NULL DEFAULT FALSE,
    checked_in_at TIMESTAMP NULL,
    checked_in_by VARCHAR(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ticket_id VARCHAR(100) NOT NULL,
    scanned_by VARCHAR(100),
    scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_info VARCHAR(255),
    result VARCHAR(50) NOT NULL,
    participant_name VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS event_settings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_name VARCHAR(150) NOT NULL DEFAULT 'ILLUMINATE',
    organizer VARCHAR(150) NOT NULL DEFAULT 'IIT Bombay E-Cell / KMCT',
    event_year VARCHAR(20) NOT NULL DEFAULT '2026',
    event_date VARCHAR(100) DEFAULT 'October 2026',
    venue VARCHAR(255) DEFAULT 'KMCT Campus Auditorium',
    logo_url VARCHAR(255) DEFAULT '/logos/ecell-iitb.png',
    theme VARCHAR(50) DEFAULT 'PURPLE_BLACK',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
